"use client";
"use no memo";

import { useState, useCallback, type DragEvent } from "react";
import { flexRender, type Header } from "@tanstack/react-table";
import { ArrowUpDown, ChevronUp, ChevronDown } from "lucide-react";
import type { TableHeaderProps, ColumnMeta } from "../types";

/**
 * Extended column meta type
 */
interface ExtendedColumnMeta extends ColumnMeta {
  isAutoGeneratedGroup?: boolean;
}

/**
 * TableHeader component with drag-and-drop column reordering
 */
export function TableHeader<TData>({
  table,
  onColumnReorder,
}: TableHeaderProps<TData>): React.ReactElement {
  const [draggingId, setDraggingId] = useState<string | null>(null);

  const handleDragStart = useCallback(
    (e: DragEvent<HTMLTableCellElement>, columnId: string) => {
      setDraggingId(columnId);
      e.dataTransfer.effectAllowed = "move";
      e.dataTransfer.setData("text/plain", columnId);
    },
    [],
  );

  const handleDrop = useCallback(
    (e: DragEvent<HTMLTableCellElement>, targetId: string) => {
      e.preventDefault();
      const sourceId = e.dataTransfer.getData("text/plain");
      if (!sourceId || sourceId === targetId) return;
      onColumnReorder?.(sourceId, targetId);
      setDraggingId(null);
    },
    [onColumnReorder],
  );

  const handleDragOver = useCallback((e: DragEvent<HTMLTableCellElement>) => {
    e.preventDefault();
  }, []);

  return (
    <thead className="bg-muted">
      {table.getHeaderGroups().map((headerGroup) => {
        const hasContent = headerGroup.headers.some((header) => {
          const meta = header.column.columnDef.meta as
            | ExtendedColumnMeta
            | undefined;
          return (
            !header.isPlaceholder &&
            header.column.columnDef.header !== undefined &&
            header.column.columnDef.header !== null &&
            !meta?.isAutoGeneratedGroup
          );
        });

        if (!hasContent) return null;

        return (
          <tr key={headerGroup.id}>
            {headerGroup.headers.map((header: Header<TData, unknown>) => {
              if (header.isPlaceholder) {
                return (
                  <th
                    key={header.id}
                    colSpan={header.colSpan}
                    className="px-3 py-3"
                  />
                );
              }

              const column = header.column;
              const colId = column.id;
              const isSorted = column.getIsSorted();
              const canSort = column.getCanSort();
              const meta = column.columnDef.meta as ColumnMeta | undefined;
              const thClass = meta?.thClass ?? "text-left";

              return (
                <th
                  key={header.id}
                  colSpan={header.colSpan}
                  draggable
                  onDragStart={(e) => handleDragStart(e, colId)}
                  onDragOver={handleDragOver}
                  onDrop={(e) => handleDrop(e, colId)}
                  className={`px-3 py-3.5 text-xs font-semibold uppercase tracking-wide text-primary ${thClass} ${
                    draggingId === colId ? "opacity-60" : ""
                  }`}
                >
                  <button
                    type="button"
                    className={`flex items-center gap-1 ${
                      canSort ? "cursor-pointer select-none" : ""
                    }`}
                    onClick={
                      canSort ? column.getToggleSortingHandler() : undefined
                    }
                    disabled={!canSort}
                  >
                    {flexRender(column.columnDef.header, header.getContext())}

                    {canSort && (
                      <>
                        {isSorted === "asc" && (
                          <ChevronUp size={14} className="ml-1" />
                        )}
                        {isSorted === "desc" && (
                          <ChevronDown size={14} className="ml-1" />
                        )}
                        {!isSorted && (
                          <ArrowUpDown size={14} className="ml-1" />
                        )}
                      </>
                    )}
                  </button>
                </th>
              );
            })}
          </tr>
        );
      })}
    </thead>
  );
}
