"use client";
"use no memo";

import { useMemo, useCallback, useState } from "react";
import {
  useReactTable,
  getCoreRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  type ColumnDef,
  type Row,
} from "@tanstack/react-table";
import { keepPreviousData } from "@tanstack/react-query";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner"; // Add toast import
import { useApiQuery } from "@/hooks/useApiQuery";
import { getQueryClient } from "@/lib/queryClient";
import { useAbility, Actions, Subjects, type AppAction, type AppSubject } from "@/lib/casl";
import { getModuleBinding } from "@/lib/access/moduleBindings";

import { TableHeader } from "./parts/TableHeader";
import { TableBody } from "./parts/TableBody";
import { TablePagination } from "./parts/TablePagination";
import { TableToolbar } from "./parts/TableToolbar";
import { TableErrorState } from "./parts/TableErrorState";
import { TableEmptyState } from "./parts/TableEmptyState";
import { RowActions } from "./parts/RowActions";
import { OperationModal } from "./parts/OperationModal";
import { ExportsToolbar } from "./parts/ExportsToolbar";
import { QueryBuilder } from "@/components/queryBuilder/QueryBuilder";
import { LoadingState } from "@/components/feedback/LoadingState";

import { buildStorageKey } from "./utils/buildStorageKey";
import { useTableUrlState } from "./hooks/useTableUrlState";
import { useTableQueryState } from "./hooks/useTableQueryState";
import { useColumnReorder } from "./hooks/useColumnReorder";
import { useOperationHandler } from "./hooks/useOperationHandler";
import { useValidatedOperations } from "./hooks/useValidatedOperations";
import { useEffect } from "react";
import type { ValidationResult } from "./utils/validateOperation";
import type { BaseOperationConfig } from "./types";

import type {
  DataTableProps,
  ColumnGroup,
  ColumnConfig,
  ColumnMeta,
  DisplayMode,
  PaginatedResponse,
  OperationsConfig,
} from "./types";

/**
 * Row type with id field
 */
interface RowWithId {
  id: string | number;
  [key: string]: unknown;
}

/**
 * Extended column meta for internal use
 */
interface ExtendedColumnMeta extends ColumnMeta {
  isAutoGeneratedGroup?: boolean;
}

/**
 * DataTable component - fully typed reusable table with Unified CRUD operations
 */
export function DataTable<TData extends RowWithId>({
  tag,
  title,
  subject,
  moduleKey,
  fetchData,
  columnsConfig,
  organizationId,
  organizationRequired = true,
  operations,
  exports, // Separate exports config
  showPagination = true,
  dontShowColumnSelect = false,
  actionHeader,
  filterConfig,
  validationMode = "strict",
}: DataTableProps<TData>): React.ReactElement {
  const ability = useAbility();
  const storageKey = useMemo(() => buildStorageKey(title, tag), [title, tag]);
  const { initialValues: initialFilters } = filterConfig ?? {};

  const resolvedSubject = useMemo<AppSubject | undefined>(() => {
    if (moduleKey) {
      const binding = getModuleBinding(moduleKey);
      if (binding) {
        return binding.subject;
      }

      if (process.env.NODE_ENV !== "production") {
        throw new Error(`Missing module binding for DataTable moduleKey: ${moduleKey}`);
      }
    }

    if (subject) return subject;

    const endpoint = fetchData.endpoint.toLowerCase();
    if (endpoint.includes("/users")) return Subjects.USER;
    if (endpoint.includes("/branches")) return Subjects.BRANCH;
    if (endpoint.includes("/tenants")) return Subjects.TENANT;
    if (endpoint.includes("/audit-logs")) return Subjects.AUDIT_LOG;
    return undefined;
  }, [moduleKey, subject, fetchData.endpoint]);

  const resolvedOperations = useMemo<OperationsConfig<TData> | undefined>(() => {
    if (!operations) return operations;
    if (!resolvedSubject) return operations;

    const actionMap: Record<string, AppAction> = {
      add: Actions.CREATE,
      view: Actions.READ,
      edit: Actions.UPDATE,
      complete: Actions.UPDATE,
      dismiss: Actions.UPDATE,
      delete: Actions.DELETE,
    };

    return Object.fromEntries(
      Object.entries(operations).filter(([operationKey, operation]) => {
        if (!operation) return false;
        const requiredAction = actionMap[operationKey];
        if (!requiredAction) return true;
        return ability.can(requiredAction, resolvedSubject);
      })
    ) as OperationsConfig<TData>;
  }, [operations, resolvedSubject, ability]);

  // Normalize column groups
  const normalizedColumnGroups = useMemo(() => {
    const groups: ColumnGroup<TData>[] = columnsConfig.map((group, index) => {
      const isAutoGenerated = !group.header && !group.id;
      return {
        ...group,
        id:
          group.id ??
          (typeof group.header === "string" ? group.header : `group-${index}`),
        meta: {
          ...group.meta,
          isAutoGeneratedGroup: isAutoGenerated,
        } as ExtendedColumnMeta,
        columns: group.columns.map((col: ColumnConfig<TData>) => ({
          ...col,
          meta: {
            ...(col.meta ?? {}),
            thClass: col.headerClassName ?? col.meta?.thClass ?? "",
            tdClass:
              col.cellClassName ?? col.className ?? col.meta?.tdClass ?? "",
          },
        })),
      };
    });

    // Add actions column if any action component is provided
    const hasAnyOperation =
      resolvedOperations?.add ||
      resolvedOperations?.edit ||
      resolvedOperations?.view ||
      resolvedOperations?.delete ||
      resolvedOperations?.complete ||
      resolvedOperations?.dismiss;

    if (hasAnyOperation) {
      groups.push({
        id: "actions",
        header: actionHeader ?? null,
        meta: {},
        columns: [
          {
            id: "actions",
            header: actionHeader ?? undefined,
            enableSorting: false,
            meta: {
              thClass: "w-[50px]",
              tdClass: "w-[50px]",
            },
          },
        ],
      });
    }

    return groups;
  }, [columnsConfig, resolvedOperations, actionHeader]);

  // Extract leaf column IDs
  const leafColumnIds = useMemo(() => {
    const ids: string[] = [];
    normalizedColumnGroups.forEach((group) => {
      group.columns.forEach((col) => {
        const id = col.id ?? col.accessorKey;
        if (id) ids.push(id);
      });
    });
    return ids;
  }, [normalizedColumnGroups]);

  // Table state management
  const {
    tableState,
    setPagination,
    setSorting,
    setColumnVisibility,
    setColumnOrder,
    setTableState,
  } = useTableQueryState(storageKey, leafColumnIds, initialFilters);

  const { pagination, sorting, columnVisibility, columnOrder, filters } =
    tableState;

  // Build query parameters
  const queryParams = useMemo(() => {
    const base = {
      page: pagination.pageIndex + 1,
      pageSize: pagination.pageSize,
    };

    const sortingParam =
      sorting && sorting.length > 0 ? { sorting: JSON.stringify(sorting) } : {};
    const filtersParam =
      filters && Object.keys(filters).length > 0
        ? { filters: JSON.stringify(filters) }
        : {};

    return {
      ...base,
      ...sortingParam,
      ...filtersParam,
      ...fetchData.params,
    };
  }, [pagination, sorting, filters, fetchData.params]);

  // Fetch data
  const { data, error, isLoading } = useApiQuery<PaginatedResponse<TData>>({
    key: fetchData.key,
    endpoint: fetchData.endpoint,
    method: fetchData.method,
    queryParams,
    organizationId,
    requireOrganization: organizationRequired,
    options: {
      placeholderData: keepPreviousData,
    },
  });

  const rows = useMemo(() => data?.rows ?? [], [data?.rows]);
  const rowCount = data?.rowCount ?? 0;

  // Validate all operations
  const { hasErrors, validationResults } = useValidatedOperations<TData>({
    operations,
    mode: validationMode,
    onError: (errors: Map<string, ValidationResult>) => {
      // Optional: show toast for errors in production
      if (process.env.NODE_ENV === "production") {
        console.error("[DataTable] Invalid operations detected:", errors);
      }
    },
  });

  // Show warning in UI if there are validation errors
  useEffect(() => {
    if (hasErrors && process.env.NODE_ENV === "development") {
      // Logged via hook
    }
  }, [hasErrors]);

  // Modal state
  const {
    modalOpen,
    setModalOpen,
    modalType,
    rowData,
    setModalType,
    setRowData,
    openAdd,
    openEdit,
    openView,
    openComplete,
    openDismiss,
    openDelete,
  } = useTableUrlState<TData>(rows);

  const handleOperationClick = useCallback(
    (type: string, data: TData) => {
      const operation = resolvedOperations?.[type];
      if (!operation) return;

      // Check validation
      const validation = validationResults.get(type);
      if (validation && !validation.isValid) {
        console.error(
          `[DataTable] Cannot execute "${type}":`,
          validation.errors,
        );
        toast.error(`Cannot execute ${type}: configuration error`);
        return;
      }

      // Determine if modal is needed
      const needsModal =
        operation.requiresModal ?? Boolean(operation.component);
      const needsConfirmation = Boolean(operation.confirmation);

      if (needsModal || needsConfirmation) {
        // Open modal for component-based or confirmed operations
        switch (type) {
          case "add":
            openAdd();
            break;
          case "edit":
            openEdit(data);
            break;
          case "view":
            openView(data);
            break;
          case "complete":
            openComplete(data);
            break;
          case "dismiss":
            openDismiss(data);
            break;
          case "delete":
            openDelete(data);
            break;
          default:
            setModalType(type);
            setRowData(data);
            setModalOpen(true);
            break;
        }
      } else if (operation.handler) {
        // Execute handler directly (no modal) - for operations like print, download
        Promise.resolve(operation.handler(data)).catch((error) => {
          const message =
            error instanceof Error ? error.message : "Operation failed";
          toast.error(message);
          console.error(`[DataTable] Handler error (${type}):`, error);
        });
      }
    },
    [
      resolvedOperations,
      validationResults,
      setModalType,
      setRowData,
      setModalOpen,
      openAdd,
      openEdit,
      openView,
      openComplete,
      openDismiss,
      openDelete,
    ],
  );

  // Derive current operation
  const currentOperation = useMemo(() => {
    if (!modalType || !resolvedOperations) return undefined;
    if (!modalType || !resolvedOperations) return undefined;
    return resolvedOperations[modalType] as BaseOperationConfig<TData> | undefined;
  }, [modalType, resolvedOperations]);

  const modalDisplayMode: DisplayMode =
    currentOperation?.displayMode ?? "sheet";

  // Operation handler with validation
  const { execute, isLoading: isOperationLoading } = useOperationHandler({
    operationKey: modalType ?? "",
    operation: currentOperation,
    organizationId,
    onSuccess: () => setModalOpen(false),
    validationMode,
  });

  // Build table columns with action handlers
  const tableColumns = useMemo(() => {
    return normalizedColumnGroups.map((group) => ({
      ...group,
      columns: group.columns.map((col) => {
        if (col.id === "actions") {
          return {
            ...col,
            cell: ({ row }: { row: Row<TData> }) => (
              <RowActions<TData>
                row={row}
                operations={resolvedOperations}
                onOperationClick={handleOperationClick}
              />
            ),
          };
        }
        return col;
      }),
    })) as ColumnDef<TData>[];
  }, [normalizedColumnGroups, resolvedOperations, handleOperationClick]);

  // React Table instance
  const table = useReactTable({
    data: rows,
    columns: tableColumns,
    getCoreRowModel: getCoreRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    getSortedRowModel: getSortedRowModel(),
    manualPagination: true,
    manualSorting: true,
    rowCount,
    defaultColumn: {
      cell: ({ getValue }) => <span>{String(getValue() ?? "")}</span>,
      enableSorting: false,
    },
    enableSorting: true,
    state: {
      pagination,
      sorting,
      columnVisibility,
      columnOrder,
    },
    onPaginationChange: setPagination,
    onSortingChange: setSorting,
    onColumnVisibilityChange: setColumnVisibility,
    onColumnOrderChange: setColumnOrder,
  });

  const handleColumnReorder = useColumnReorder(
    setTableState,
    leafColumnIds,
    table,
  );

  // Export state
  const [isExporting, setIsExporting] = useState<string | null>(null);

  // Handle export
  const handleExport = useCallback(
    async (exportType: string) => {
      const exportConfig = exports?.[exportType];
      if (!exportConfig) {
        console.error(`[DataTable] Export type "${exportType}" not configured`);
        return;
      }

      // Get visible columns
      const visibleColumns = table
        .getAllLeafColumns()
        .filter((col) => col.getIsVisible())
        .map((col) => col.columnDef);

      try {
        setIsExporting(exportType);

        // Execute export handler
        await Promise.resolve(
          exportConfig.handler(tag, rows, visibleColumns as ColumnDef<TData>[]),
        );
      } catch (error) {
        console.error(`[DataTable] Export error (${exportType}):`, error);
        toast.error(`Failed to export ${exportType.toUpperCase()}`);
      } finally {
        setIsExporting(null);
      }
    },
    [exports, table, tag, rows],
  );

  // Refresh handler
  const refresh = useCallback(() => {
    const queryKey = Array.isArray(fetchData.key)
      ? fetchData.key
      : [fetchData.key];
    const queryClient = getQueryClient();
    void queryClient.invalidateQueries({
      queryKey,
      exact: false,
      refetchType: "active", // Only refetch the currently active query, not all cached entries
    });
  }, [fetchData.key]);

  // Error state
  if (error) {
    return (
      <TableErrorState
        onRetry={() => {
          setTableState({
            pagination: { pageIndex: 0, pageSize: 10 },
            sorting: [],
            columnVisibility: {},
            columnOrder: [],
            filters: initialFilters ?? {},
          });
          setTimeout(refresh, 100);
        }}
      />
    );
  }

  // Loading state
  if (isLoading) {
    return (
      <div className="w-full rounded-lg border bg-card p-6">
        <LoadingState label="Loading data..." />
      </div>
    );
  }

  return (
    <>
      <div className="bg-background rounded-lg flex flex-col flex-1 min-h-0">
        {/* QueryBuilder filters */}
        {filterConfig?.schema && (
          <div className="py-2">
            <QueryBuilder
              schema={filterConfig.schema}
              onSubmit={(newFilters) => {
                setTableState((prev) => ({
                  ...prev,
                  filters: newFilters ?? {},
                  pagination: { ...prev.pagination, pageIndex: 0 },
                }));
              }}
              initialValue={filters}
            />
          </div>
        )}
        <div className="border shadow-lg rounded-lg">
          <div className="px-6 py-4 bg-muted flex flex-col md:flex-row md:justify-between md:items-center gap-4 flex-none rounded-t-lg">
            <h2 className="text-2xl font-semibold text-primary flex items-center">
              Manage {title}
              {rowCount > 0 && (
                <Badge className="ml-3 bg-secondary text-secondary-foreground font-normal">
                  {rowCount} items
                </Badge>
              )}
            </h2>

            <TableToolbar
              table={table}
              onRefresh={refresh}
              onAdd={resolvedOperations?.add ? openAdd : undefined}
              addButtonText={resolvedOperations?.add?.label ?? "Add Item"}
              showColumnMenu={!dontShowColumnSelect}
              visibilityState={columnVisibility}
            />
          </div>

          {/* Exports toolbar */}
          <ExportsToolbar
            exports={exports}
            onExport={handleExport}
            isExporting={isExporting}
          />

          <div className="overflow-auto flex-1">
            <table className="w-full border-collapse">
              <TableHeader
                table={table}
                onColumnReorder={handleColumnReorder}
              />
              {rows.length === 0 ? (
                <TableEmptyState colSpan={table.getAllLeafColumns().length} />
              ) : (
                <TableBody
                  key={`${rows[0]?.id ?? "empty"}-${rows.length}-${pagination.pageSize}-${JSON.stringify(columnVisibility)}-${JSON.stringify(columnOrder)}`}
                  table={table}
                />
              )}
            </table>
          </div>

          <div className="px-6 border-t flex-none bg-card py-2 rounded-b-lg">
            <TablePagination table={table} showPagination={showPagination} />
          </div>
        </div>
      </div>

      <OperationModal
        open={modalOpen}
        onOpenChange={setModalOpen}
        modalType={modalType}
        title={title}
        operation={currentOperation}
        rowData={rowData}
        onExecute={execute}
        isLoading={isOperationLoading}
        displayMode={modalDisplayMode}
        width={currentOperation?.width}
      />
    </>
  );
}
