import type { ReactNode, ComponentType } from "react";
import type {
  ColumnDef,
  SortingState,
  PaginationState,
  VisibilityState,
  Table,
  CellContext,
  HeaderContext,
} from "@tanstack/react-table";
import type { z } from "zod";
import type { QueryParams } from "@/lib/types";
import type { AppSubject } from "@/lib/casl";

// =============================================================================
// Column Configuration Types
// =============================================================================

export interface ColumnMeta {
  thClass?: string;
  tdClass?: string;
  align?: "left" | "center" | "right";
  width?: string;
  [key: string]: unknown;
}

export interface ColumnConfig<TData> {
  id?: string;
  accessorKey?: keyof TData & string;
  header?: string | ((context: HeaderContext<TData, unknown>) => ReactNode);
  cell?: (context: CellContext<TData, unknown>) => ReactNode;
  enableSorting?: boolean;
  enableHiding?: boolean;
  headerClassName?: string;
  cellClassName?: string;
  className?: string;
  meta?: ColumnMeta;
}

export interface ColumnGroup<TData> {
  id?: string;
  header?: string | null;
  columns: ColumnConfig<TData>[];
  meta?: ColumnMeta & {
    isAutoGeneratedGroup?: boolean;
  };
}

// =============================================================================
// Filter Configuration Types
// =============================================================================

export type FilterState = Record<string, unknown>;

export interface FilterConfig {
  schema?: z.ZodObject<z.ZodRawShape>;
  initialValues?: FilterState;
}

// =============================================================================
// Table State Types
// =============================================================================

export interface TableState {
  pagination: PaginationState;
  sorting: SortingState;
  columnVisibility: VisibilityState;
  columnOrder: string[];
  filters: FilterState;
}

export interface TableStateSetters {
  setPagination: React.Dispatch<React.SetStateAction<PaginationState>>;
  setSorting: React.Dispatch<React.SetStateAction<SortingState>>;
  setColumnVisibility: React.Dispatch<React.SetStateAction<VisibilityState>>;
  setColumnOrder: React.Dispatch<React.SetStateAction<string[]>>;
  setFilters: React.Dispatch<React.SetStateAction<FilterState>>;
  setTableState: React.Dispatch<React.SetStateAction<TableState>>;
}

// =============================================================================
// Operation Configuration Types (Unified Protocol)
// =============================================================================

export type OperationType = "add" | "edit" | "view" | "delete" | "complete" | "dismiss";

export type DisplayMode = "dialog" | "sheet";

/**
 * Props passed to operation components
 */
export interface OperationComponentProps<TData> {
  data?: TData;
  onSuccess: () => void;
  onCancel: () => void;
}

/**
 * Base configuration for any operation
 * IMPORTANT: Only ONE of component, api, or handler should be provided
 */
export interface BaseOperationConfig<TData = unknown> {
  /** Option 1: Custom React component for full UI control */
  component?: ComponentType<OperationComponentProps<TData>>;
  
  /** Option 2: API endpoint configuration for server calls */
  api?: {
    endpoint: string;
    method?: "POST" | "PUT" | "DELETE" | "PATCH"; // GET removed as it is not a mutation
    key: string | readonly unknown[];
    /** Next.js cache tags to revalidate after mutation */
    revalidateNextTags?: string[];
    /** Next.js paths to revalidate after mutation */
    revalidatePaths?: string[];
  };

  /** Option 3: Custom function handler for client-side logic */
  handler?: (data?: TData) => void | Promise<void>;
  
  /** Optional: Confirmation settings */
  confirmation?: {
    title?: string;
    message?: string;
    confirmText?: string;
    cancelText?: string;
  };
  
  /** Display mode for component-based operations */
  displayMode?: DisplayMode;

  /** Width size for sheet/dialog: 'sm' | 'md' | 'lg' | 'xl' | 'full' */
  width?: 'sm' | 'md' | 'lg' | 'xl' | 'full';
  
  /** Label for buttons (e.g. "Add User") */
  label?: string;
  
  /** Custom title for the modal (overrides auto-generated title) */
  modalTitle?: string;

  /** Custom description for the modal (overrides auto-generated description) */
  modalDescription?: string;

  icon?: ReactNode;

  /** Conditional display for row-level actions */
  isVisible?: (data: TData) => boolean;

  /** Override modal requirement (default: true for component, false for handler) */
  requiresModal?: boolean;
}

/**
 * Validated operation config - ensures only one execution method
 */
export type ValidatedOperationConfig<TData> = 
  | { component: ComponentType<OperationComponentProps<TData>>; api?: never; handler?: never }
  | { api: NonNullable<BaseOperationConfig<TData>['api']>; component?: never; handler?: never }
  | { handler: NonNullable<BaseOperationConfig<TData>['handler']>; component?: never; api?: never };

/**
 * Complete operations registry
 */
export interface OperationsConfig<TData> {
  add?: BaseOperationConfig<TData>;
  edit?: BaseOperationConfig<TData>;
  view?: BaseOperationConfig<TData>;
  delete?: BaseOperationConfig<TData>;
  complete?: BaseOperationConfig<TData>;
  dismiss?: BaseOperationConfig<TData>;
  [key: string]: BaseOperationConfig<TData> | undefined;
}

// =============================================================================
// API & Data Types
// =============================================================================

export interface PaginatedResponse<TData> {
  rows: TData[];
  rowCount: number;
}

/**
 * Row type with id field requirement
 */
export interface RowWithId {
  id: string | number;
  [key: string]: unknown;
}

// =============================================================================
// Sub-component Props
// =============================================================================

export interface TableHeaderProps<TData> {
  table: Table<TData>;
  onColumnReorder?: (sourceId: string, targetId: string) => void;
}

export interface TableBodyProps<TData> {
  table: Table<TData>;
}

export interface TablePaginationProps<TData> {
  table: Table<TData>;
  showPagination?: boolean;
}

export interface TableToolbarProps<TData> {
  table: Table<TData>;
  onRefresh?: () => void;
  onAdd?: () => void;
  addButtonText?: string;
  showColumnMenu?: boolean;
  visibilityState?: VisibilityState;
}

export interface TableEmptyStateProps {
  colSpan: number;
  message?: string;
}

export interface TableErrorStateProps {
  onRetry?: () => void;
  message?: string;
}

// =============================================================================
// Export Configuration Types
// =============================================================================

/**
 * Export handler function signature
 */
export type ExportHandlerFunc<TData> = (
  tag: string,
  rows: TData[],
  visibleColumns: ColumnDef<TData>[]
) => void | Promise<void>;

/**
 * Export configuration for table-level bulk exports
 */
export interface ExportConfig<TData = unknown> {
  /** Export handler function */
  handler: ExportHandlerFunc<TData>;
  
  /** Button label (default: format name) */
  label?: string;
  
  /** Icon to display */
  icon?: ReactNode;
  
  /** Tooltip text */
  tooltip?: string;
}

/**
 * Exports configuration - separate from operations
 */
export interface ExportsConfig<TData> {
  pdf?: ExportConfig<TData>;
  csv?: ExportConfig<TData>;
  excel?: ExportConfig<TData>;
  json?: ExportConfig<TData>;
  xml?: ExportConfig<TData>;
  // Allow custom export formats
  [key: string]: ExportConfig<TData> | undefined;
}

// =============================================================================
// Main DataTable Props
// =============================================================================

export interface DataTableProps<TData extends RowWithId> {
  tag: string;
  title: string;
  subject?: AppSubject;
  moduleKey?: string;
  
  /** Data fetching configuration */
   fetchData: {
     endpoint: string;
     method?: "GET" | "POST";
     key: string | readonly unknown[];
     params?: QueryParams;
   };
  
  columnsConfig: ColumnGroup<TData>[];
  
  /** Unified operations configuration (Row-level) */
  operations?: OperationsConfig<TData>;

  /** Table-level bulk exports (PDF, CSV, Excel, etc.) */
  exports?: ExportsConfig<TData>;
  
  organizationId?: string;
  organizationRequired?: boolean;
  filterConfig?: FilterConfig;
  
  /** Legacy or optional overrides */
  showPagination?: boolean;
  dontShowColumnSelect?: boolean;
  actionHeader?: string;
  
  /** 
   * Validation mode for operations
   * - 'strict': Throw errors if multiple execution methods provided (recommended)
   * - 'priority': Use priority order (component > api > handler) with warnings
   * @default 'strict'
   */
  validationMode?: "strict" | "priority";
}

export type ModalType = OperationType | string | null;
