import { db } from "../../../db/index.js";
import { rssSources, feedItems } from "../automation.schema.js";
import { blogPosts } from "../../blogPosts/blogPosts.schema.js";
import { platformSettings } from "../../../db/schema/settings.js";
import { prompts as promptsTable } from "../../prompts/prompts.schema.js";
import { eq, desc, inArray, and, isNull } from "drizzle-orm";
import { fetchRssFeed } from "./rssFetcher.js";
import { chatCompletion } from "../../settings/llm/completion.js";
import { buildBlogPostPrompt } from "../../blogPosts/prompts/generate.js";
import {
    slugify,
    calculateReadTime,
    extractTableOfContents,
    extractContentImageIds,
    robustJsonParse,
} from "../../../utils/text.js";

export class AutomationService {
    /**
     * Sync all active RSS feeds
     */
    static async syncAllFeeds() {
        const activeSources = await db
            .select()
            .from(rssSources)
            .where(eq(rssSources.isActive, true));

        console.log("[RSS SYNC] Starting sync for " + activeSources.length + " sources");

        for (const source of activeSources) {
            try {
                const items = await fetchRssFeed(source.url);
                let newCount = 0;

                for (const item of items) {
                    const existing = await db
                        .select()
                        .from(feedItems)
                        .where(eq(feedItems.guid, item.guid || ""))
                        .limit(1);

                    if (existing.length === 0) {
                        await db.insert(feedItems).values({
                            sourceId: source.id,
                            guid: item.guid || item.link || "",
                            url: item.link || "",
                            title: item.title || "Untitled",
                            description: item.summary || "",
                            content: item.content || "",
                            author: item.creator || "",
                            publishedAt: item.pubDate ? new Date(item.pubDate) : new Date(),
                            processingStatus: "unprocessed",
                        });
                        newCount++;
                    }
                }

                await db
                    .update(rssSources)
                    .set({ lastSyncedAt: new Date(), updatedAt: new Date() })
                    .where(eq(rssSources.id, source.id));

                console.log("[RSS SYNC] Finished source \"" + source.name + "\": " + newCount + " new items");
            } catch (err) {
                console.error("[RSS SYNC] Failed for source \"" + source.name + "\":", err);
            }
        }
    }

    /**
     * Select a topic and generate a draft blog post
     */
    static async autoGenerateDraft() {
        // 1. Get the newest unprocessed items — no date filter, just grab whatever is available
        const items = await db
            .select({
                id: feedItems.id,
                title: feedItems.title,
                description: feedItems.description,
                sourceId: feedItems.sourceId,
            })
            .from(feedItems)
            .where(eq(feedItems.processingStatus, "unprocessed"))
            .orderBy(desc(feedItems.publishedAt))
            .limit(50);

        console.log("[RSS AUTO] Found " + items.length + " unprocessed feed items");

        if (items.length === 0) {
            return { success: false, message: "No new feed items to process" };
        }

        // Log the titles so we can see what's being sent
        console.log("[RSS AUTO] Feed item titles being sent:");
        items.forEach((it, idx) => console.log("  [" + idx + "] " + it.title));

        // 2. Semantic Deduplication: Get recent blog titles
        const recentPosts = await db
            .select({ title: blogPosts.title })
            .from(blogPosts)
            .orderBy(desc(blogPosts.createdAt))
            .limit(20);

        const recentTitles = recentPosts.map((p) => p.title).join("\n- ");
        console.log("[RSS AUTO] Recent blog titles for dedup: " + recentPosts.length);

        // 3. LLM Prompt 1: Topic Selection
        const feedContext = items
            .map((it, idx) => "[" + idx + "] " + it.title + "\n    " + (it.description?.slice(0, 150) || ""))
            .join("\n");

        const recentSection = recentTitles ? "- " + recentTitles : "(none)";

        const [rssPromptSetting] = await db
          .select()
          .from(promptsTable)
          .where(
            and(
              eq(promptsTable.module, "prompt_rss_topic"),
              eq(promptsTable.isActive, true),
              isNull(promptsTable.deletedAt)
            )
          )
          .limit(1);
        
        let TOPIC_SELECTION_PROMPT = rssPromptSetting?.content ? rssPromptSetting.content : [
            "You are a content strategist. Pick the best topic from the feed items below for an India-focused blog post.",
            "",
            "RECENT POSTS (avoid duplicating):",
            "{RECENT_POSTS}",
            "",
            "FEED ITEMS:",
            "{FEED_ITEMS}",
            "",
            "Pick the most compelling topic. Prefer India-relevant topics but any significant global topic with Indian impact is fine.",
            "",
            "Respond with ONLY this JSON:",
            '{"selectedTitle": "Your chosen title", "reasoning": "Why you chose it", "sourceIndices": [0, 1]}'
        ].join("\n");
        
        TOPIC_SELECTION_PROMPT = TOPIC_SELECTION_PROMPT
            .replace("{RECENT_POSTS}", recentSection)
            .replace("{FEED_ITEMS}", feedContext);

        console.log("[RSS AUTO] Sending topic selection prompt to LLM...");

        const selectionRaw = await chatCompletion({
            messages: [{ role: "user", content: TOPIC_SELECTION_PROMPT }],
            temperature: 0.3,
        });

        console.log("[RSS AUTO] LLM raw response (first 500 chars): " + selectionRaw.slice(0, 500));

        // Parse the response
        let selectedTitle = "";
        let sourceIndices: number[] = [];

        try {
            let jsonText = selectionRaw
                .replace(/^```(?:json)?\s*/i, "")
                .replace(/\s*```$/i, "")
                .trim();

            const firstBrace = jsonText.indexOf("{");
            const lastBrace = jsonText.lastIndexOf("}");
            if (firstBrace !== -1 && lastBrace > firstBrace) {
                jsonText = jsonText.substring(firstBrace, lastBrace + 1);
            }

            const parsed = JSON.parse(jsonText);
            selectedTitle = parsed.selectedTitle || parsed.selected_title || "";
            sourceIndices = Array.isArray(parsed.sourceIndices)
                ? parsed.sourceIndices
                : Array.isArray(parsed.source_indices)
                    ? parsed.source_indices
                    : [];

            console.log("[RSS AUTO] Parsed title: \"" + selectedTitle + "\"");
            console.log("[RSS AUTO] Parsed sourceIndices: [" + sourceIndices.join(", ") + "]");
        } catch (parseErr) {
            console.warn("[RSS AUTO] JSON parse failed, using regex fallback...");

            const titleMatch = selectionRaw.match(/"selectedTitle"\s*:\s*"((?:[^"\\]|\\[\s\S])*?)"/i);
            if (titleMatch) {
                selectedTitle = titleMatch[1].replace(/\\"/g, '"').replace(/\\n/g, "\n");
            }

            const indicesMatch = selectionRaw.match(/"sourceIndices"\s*:\s*\[([^\]]*)\]/i);
            if (indicesMatch) {
                const nums = indicesMatch[1].match(/\d+/g);
                sourceIndices = nums ? nums.map(Number) : [];
            }

            console.log("[RSS AUTO] Regex fallback title: \"" + selectedTitle + "\"");
            console.log("[RSS AUTO] Regex fallback sourceIndices: [" + sourceIndices.join(", ") + "]");
        }

        // If we got a title but no sourceIndices, default to [0]
        if (selectedTitle && sourceIndices.length === 0) {
            console.log("[RSS AUTO] No sourceIndices found, defaulting to [0]");
            sourceIndices = [0];
        }

        // If we still have no title, use the first feed item as fallback
        if (!selectedTitle) {
            console.log("[RSS AUTO] No title from LLM, using first feed item as fallback");
            selectedTitle = items[0].title;
            sourceIndices = [0];
        }

        console.log("[RSS AUTO] Final selected title: \"" + selectedTitle + "\"");
        console.log("[RSS AUTO] Final sourceIndices: [" + sourceIndices.join(", ") + "]");

        const selectedItemIds = sourceIndices
            .map((idx: number) => items[idx]?.id)
            .filter(Boolean);

        // 4. LLM Prompt 2: Content Generation
        const [blogPromptSetting] = await db
          .select()
          .from(promptsTable)
          .where(
            and(
              eq(promptsTable.module, "prompt_blog_post"),
              eq(promptsTable.isActive, true),
              isNull(promptsTable.deletedAt)
            )
          )
          .limit(1);
        const baseMessages = buildBlogPostPrompt(selectedTitle, blogPromptSetting?.content ? blogPromptSetting.content : null);
        const sourceMaterial = sourceIndices
            .map((idx: number) => "SOURCE: " + items[idx]?.title + "\nDETAILS: " + items[idx]?.description)
            .join("\n\n");

        const lastMsg = baseMessages[baseMessages.length - 1];
        lastMsg.content += "\n\nUSE THIS SOURCE MATERIAL AS GROUNDING:\n" + sourceMaterial + "\n\nStrictly prioritize an India-centric analysis and investigative depth.";

        console.log("[RSS AUTO] Sending content generation prompt to LLM...");

        const generateResponseRaw = await chatCompletion({
            messages: baseMessages,
            temperature: 0.7,
            maxTokens: 16000,
            jsonMode: true,
        });

        console.log("[RSS AUTO] Content generation response received (" + generateResponseRaw.length + " chars)");
        console.log("[RSS AUTO] Raw content response (first 1000 chars): " + generateResponseRaw.slice(0, 1000));

        const generateResponse = robustJsonParse<any>(generateResponseRaw, {
            slug: "",
            metaTitle: "",
            metaDescription: "",
            metaKeywords: "",
            excerpt: "",
            content: generateResponseRaw,
        });

        // FAQ logging
        console.log("[RSS AUTO] Parsed data keys: " + Object.keys(generateResponse).join(", "));
        console.log("[RSS AUTO] FAQ items found: " + (generateResponse.faq?.length || 0));
        if (generateResponse.faq?.length > 0) {
            console.log("[RSS AUTO] First FAQ: " + JSON.stringify(generateResponse.faq[0]));
        }

        // Update statuses
        if (selectedItemIds.length > 0) {
            await db.update(feedItems)
                .set({ processingStatus: "processed" })
                .where(inArray(feedItems.id, selectedItemIds));
            console.log("[RSS AUTO] Marked " + selectedItemIds.length + " feed items as processed.");
        }

        // 5. Save as Draft
        const content = generateResponse.content || "";
        const faq = Array.isArray(generateResponse.faq) ? generateResponse.faq : [];
        const [insertedPost] = await db.insert(blogPosts).values({
            title: selectedTitle,
            slug: generateResponse.slug || slugify(selectedTitle),
            excerpt: generateResponse.excerpt || "",
            content: content,
            metaTitle: generateResponse.metaTitle || selectedTitle,
            metaDescription: generateResponse.metaDescription || "",
            metaKeywords: generateResponse.metaKeywords || "",
            faq: faq,
            status: "draft",
            tableOfContents: extractTableOfContents(content),
            readTimeMinutes: calculateReadTime(content),
            contentImageFileIds: extractContentImageIds(content),
            authorType: "platform",
        }).returning();

        console.log("[RSS AUTO] Draft saved: \"" + insertedPost.title + "\" (" + insertedPost.id + ")");

        return {
            success: true,
            data: insertedPost,
            title: selectedTitle,
        };
    }
}
