import { z } from "zod";
import type { FastifyPluginAsync } from "fastify";
import { db } from "../../../db/index.js";
import { rssSources } from "../automation.schema.js";
import { AutomationService } from "../services/automation.service.js";
import { createCrudRoutes } from "../../../core/crudFactory.js";
import { rateLimitConfig } from "../../../core/rateLimit.js";
import { CRUD_ACCESS } from "../../../access/crudAccess.js";
import { requirePlatformAuth } from "../../../middlewares/auth.guard.js";
import { platformAbilityGuard } from "../../../middlewares/ability.guard.js";
import { ACTIONS, SUBJECTS } from "../../rbac/public/permissions.js";

const { insertSchema, updateSchema } = {
    insertSchema: z.object({
        name: z.string().min(1),
        url: z.string().url(),
        isActive: z.boolean().optional(),
    }),
    updateSchema: z.object({
        name: z.string().min(1).optional(),
        url: z.string().url().optional(),
        isActive: z.boolean().optional(),
    }),
};

const idParamsSchema = z.object({ id: z.string().uuid() });

const crudRoutes = createCrudRoutes({
    table: rssSources,
    cache: {
        tag: "rssSources",
        keyPrefix: "rssSource",
    },
    searchableColumns: ["name", "url"],
    columnMap: {
        name: rssSources.name,
        url: rssSources.url,
        isActive: rssSources.isActive,
        lastSyncedAt: rssSources.lastSyncedAt,
    },
    validation: {
        createBody: insertSchema,
        updateBody: updateSchema,
        idParams: idParamsSchema,
    },
    access: CRUD_ACCESS.rssSources,
    rateLimit: {
        list: rateLimitConfig.user,
        create: rateLimitConfig.user,
        update: rateLimitConfig.user,
        delete: rateLimitConfig.user,
    },
});

export const automationRoutes: FastifyPluginAsync = async (fastify) => {
    // Register CRUD for RSS Sources
    await fastify.register(crudRoutes);

    // Manual Trigger: Sync RSS
    fastify.post(
        "/sync",
        {
            preHandler: [
                requirePlatformAuth(),
                platformAbilityGuard(ACTIONS.UPDATE, SUBJECTS.PLATFORM_SETTINGS),
            ],
        },
        async (request, reply) => {
            // Run sync in background
            AutomationService.syncAllFeeds().catch(console.error);
            return { success: true, message: "Sync started in background" };
        }
    );

    // Manual Trigger: Generate Draft from RSS
    fastify.post(
        "/generate",
        {
            preHandler: [
                requirePlatformAuth(),
                platformAbilityGuard(ACTIONS.CREATE, SUBJECTS.BLOG_POST),
            ],
            config: { rateLimit: rateLimitConfig.user },
        },
        async (request, reply) => {
            try {
                const result = await AutomationService.autoGenerateDraft();
                // Return a lean response — frontend only needs success, title, and message
                if (result.success) {
                    return {
                        success: true,
                        title: result.title,
                        postId: result.data?.id,
                        message: "Draft generated successfully",
                    };
                }
                return result;
            } catch (err) {
                console.error("[RSS GENERATE ROUTE] Error:", err);
                request.log.error(err);
                return reply.status(500).send({
                    success: false,
                    error: { message: err instanceof Error ? err.message : "Generation failed" }
                });
            }
        }
    );
};
