import { z } from "zod";
import type { FastifyPluginAsync } from "fastify";
import { db } from "../../../db/index.js";
import { rssSources, automationTopicSessions, automationTopicCandidates } from "../automation.schema.js";
import { blogCategories } from "../../blogCategories/blogCategories.schema.js";
import { blogTags } from "../../blogTags/blogTags.schema.js";
import { blogPosts } from "../../blogPosts/blogPosts.schema.js";
import { AutomationService } from "../services/automation.service.js";
import { createCrudRoutes } from "../../../core/crudFactory.js";
import { rateLimitConfig } from "../../../core/rateLimit.js";
import { CRUD_ACCESS } from "../../../access/crudAccess.js";
import { requirePlatformAuth } from "../../../middlewares/auth.guard.js";
import { platformAbilityGuard } from "../../../middlewares/ability.guard.js";
import { ACTIONS, SUBJECTS } from "../../rbac/public/permissions.js";
import { desc, eq, and, inArray } from "drizzle-orm";

const { insertSchema, updateSchema } = {
    insertSchema: z.object({
        name: z.string().min(1),
        url: z.string().url(),
        isActive: z.boolean().optional(),
    }),
    updateSchema: z.object({
        name: z.string().min(1).optional(),
        url: z.string().url().optional(),
        isActive: z.boolean().optional(),
    }),
};

const idParamsSchema = z.object({ id: z.string().uuid() });

const crudRoutes = createCrudRoutes({
    table: rssSources,
    cache: {
        tag: "rssSources",
        keyPrefix: "rssSource",
    },
    searchableColumns: ["name", "url"],
    columnMap: {
        name: rssSources.name,
        url: rssSources.url,
        isActive: rssSources.isActive,
        lastSyncedAt: rssSources.lastSyncedAt,
    },
    validation: {
        createBody: insertSchema,
        updateBody: updateSchema,
        idParams: idParamsSchema,
    },
    access: CRUD_ACCESS.rssSources,
    rateLimit: {
        list: rateLimitConfig.user,
        create: rateLimitConfig.user,
        update: rateLimitConfig.user,
        delete: rateLimitConfig.user,
    },
});

export const automationRoutes: FastifyPluginAsync = async (fastify) => {
    // Register CRUD for RSS Sources
    await fastify.register(crudRoutes);

    // Manual Trigger: Sync RSS
    fastify.post(
        "/sync",
        {
            preHandler: [
                requirePlatformAuth(),
                platformAbilityGuard(ACTIONS.UPDATE, SUBJECTS.PLATFORM_SETTINGS),
            ],
        },
        async (request, reply) => {
            // Run sync in background
            AutomationService.syncAllFeeds().catch(console.error);
            return { success: true, message: "Sync started in background" };
        }
    );

    // Manual Trigger: Sync RSS and send Telegram topic shortlist
    fastify.post(
        "/sync-and-notify",
        {
            preHandler: [
                requirePlatformAuth(),
                platformAbilityGuard(ACTIONS.UPDATE, SUBJECTS.PLATFORM_SETTINGS),
            ],
            config: { rateLimit: rateLimitConfig.user },
        },
        async (request, reply) => {
            try {
                const result = await AutomationService.syncAndNotifyTelegram(10);
                return result;
            } catch (err) {
                request.log.error(err);
                return reply.status(500).send({
                    success: false,
                    error: { message: err instanceof Error ? err.message : "Sync and notify failed" },
                });
            }
        }
    );

    // Manual Trigger: Generate Draft from RSS
    fastify.post(
        "/generate",
        {
            preHandler: [
                requirePlatformAuth(),
                platformAbilityGuard(ACTIONS.CREATE, SUBJECTS.BLOG_POST),
            ],
            config: { rateLimit: rateLimitConfig.user },
        },
        async (request, reply) => {
            try {
                const result = await AutomationService.autoGenerateDraft();
                // Return a lean response — frontend only needs success, title, and message
                if (result.success) {
                    return {
                        success: true,
                        title: result.title,
                        postId: result.data?.id,
                        message: "Draft generated successfully",
                    };
                }
                return result;
            } catch (err) {
                console.error("[RSS GENERATE ROUTE] Error:", err);
                request.log.error(err);
                return reply.status(500).send({
                    success: false,
                    error: { message: err instanceof Error ? err.message : "Generation failed" }
                });
            }
        }
    );

    // Get automation sessions with pagination and filtering
    fastify.get(
        "/sessions",
        {
            preHandler: [
                requirePlatformAuth(),
                platformAbilityGuard(ACTIONS.READ, SUBJECTS.PLATFORM_SETTINGS),
            ],
            config: { rateLimit: rateLimitConfig.user },
        },
        async (request, reply) => {
            try {
                const querySchema = z.object({
                    page: z.coerce.number().int().min(0).default(0),
                    pageSize: z.coerce.number().int().min(1).max(100).default(20),
                    status: z
                        .enum([
                            "pending",
                            "selected",
                            "generated",
                            "categorizing",
                            "tagging",
                            "completed",
                            "failed",
                            "expired",
                            "cancelled",
                        ])
                        .optional(),
                });

                const query = querySchema.parse(request.query);

                const safePage = query.page;
                const safePageSize = query.pageSize;

                const whereConditions = query.status
                    ? eq(automationTopicSessions.status, query.status)
                    : undefined;

                const sessions = await db
                    .select({
                        id: automationTopicSessions.id,
                        status: automationTopicSessions.status,
                        workflowStep: automationTopicSessions.workflowStep,
                        telegramChatId: automationTopicSessions.telegramChatId,
                        telegramMessageId: automationTopicSessions.telegramMessageId,
                        selectedCandidateRank: automationTopicSessions.selectedCandidateRank,
                        generatedPostId: automationTopicSessions.generatedPostId,
                        assignedCategoryId: automationTopicSessions.assignedCategoryId,
                        assignedSecondaryCategoryId: automationTopicSessions.assignedSecondaryCategoryId,
                        selectedTagIds: automationTopicSessions.selectedTagIds,
                        errorMessage: automationTopicSessions.errorMessage,
                        expiresAt: automationTopicSessions.expiresAt,
                        createdAt: automationTopicSessions.createdAt,
                        updatedAt: automationTopicSessions.updatedAt,
                    })
                    .from(automationTopicSessions)
                    .where(whereConditions)
                    .orderBy(desc(automationTopicSessions.createdAt))
                    .limit(safePageSize)
                    .offset(safePage * safePageSize);

                // Enrich with candidate, post, category, and tags data
                const enrichedSessions = await Promise.all(
                    sessions.map(async (session) => {
                        const [candidate] = session.selectedCandidateRank !== null
                            ? await db
                                .select({
                                    title: automationTopicCandidates.title,
                                    description: automationTopicCandidates.description,
                                    sourceUrl: automationTopicCandidates.sourceUrl,
                                })
                                .from(automationTopicCandidates)
                                .where(
                                    and(
                                        eq(automationTopicCandidates.sessionId, session.id),
                                        eq(automationTopicCandidates.rank, session.selectedCandidateRank!),
                                    )
                                )
                                .limit(1)
                            : [];

                        const [post] = session.generatedPostId
                            ? await db
                                .select({
                                    id: blogPosts.id,
                                    title: blogPosts.title,
                                    slug: blogPosts.slug,
                                    status: blogPosts.status,
                                })
                                .from(blogPosts)
                                .where(eq(blogPosts.id, session.generatedPostId!))
                                .limit(1)
                            : [];

                        const [category] = session.assignedCategoryId
                            ? await db
                                .select({
                                    id: blogCategories.id,
                                    name: blogCategories.name,
                                })
                                .from(blogCategories)
                                .where(eq(blogCategories.id, session.assignedCategoryId!))
                                .limit(1)
                            : [];

                        const [secondaryCategory] = session.assignedSecondaryCategoryId
                            ? await db
                                .select({
                                    id: blogCategories.id,
                                    name: blogCategories.name,
                                })
                                .from(blogCategories)
                                .where(eq(blogCategories.id, session.assignedSecondaryCategoryId!))
                                .limit(1)
                            : [];

                        const tags = session.selectedTagIds && session.selectedTagIds.length > 0
                            ? await db
                                .select({
                                    id: blogTags.id,
                                    name: blogTags.name,
                                })
                                .from(blogTags)
                                .where(inArray(blogTags.id, session.selectedTagIds))
                            : [];

                        return {
                            ...session,
                            candidate: candidate || null,
                            post: post || null,
                            category: category || null,
                            secondaryCategory: secondaryCategory || null,
                            tags: tags || [],
                        };
                    })
                );

                const total = sessions.length;

                return reply.send({ sessions: enrichedSessions, total });
            } catch (err) {
                request.log.error(err);
                return reply.status(500).send({
                    success: false,
                    error: { message: err instanceof Error ? err.message : "Failed to fetch sessions" },
                });
            }
        }
    );

    // Expire old pending sessions
    fastify.post(
        "/sessions/expire",
        {
            preHandler: [
                requirePlatformAuth(),
                platformAbilityGuard(ACTIONS.UPDATE, SUBJECTS.PLATFORM_SETTINGS),
            ],
            config: { rateLimit: rateLimitConfig.user },
        },
        async (request, reply) => {
            try {
                await AutomationService.expireOldSessions();
                return { success: true, message: "Old sessions expired" };
            } catch (err) {
                request.log.error(err);
                return reply.status(500).send({
                    success: false,
                    error: { message: err instanceof Error ? err.message : "Failed to expire sessions" },
                });
            }
        }
    );

    // Publish or keep draft action after Telegram assignment
    fastify.post(
        "/sessions/:sessionId/publish",
        {
            preHandler: [
                requirePlatformAuth(),
                platformAbilityGuard(ACTIONS.UPDATE, SUBJECTS.BLOG_POST),
            ],
            config: { rateLimit: rateLimitConfig.user },
        },
        async (request, reply) => {
            try {
                const { sessionId } = request.params as { sessionId: string };
                const body = request.body as { action?: "publish" | "keep_draft" };
                const action = body.action || "keep_draft";

                const [session] = await db
                    .select({ generatedPostId: automationTopicSessions.generatedPostId })
                    .from(automationTopicSessions)
                    .where(eq(automationTopicSessions.id, sessionId))
                    .limit(1);

                if (!session || !session.generatedPostId) {
                    return reply.status(404).send({
                        success: false,
                        error: { message: "Session or draft not found" },
                    });
                }

                if (action === "publish") {
                    await db
                        .update(blogPosts)
                        .set({
                            status: "published",
                            publishedAt: new Date(),
                            updatedAt: new Date(),
                        })
                        .where(eq(blogPosts.id, session.generatedPostId));
                }

                await db
                    .update(automationTopicSessions)
                    .set({
                        status: "completed",
                        workflowStep: "completed",
                        updatedAt: new Date(),
                    })
                    .where(eq(automationTopicSessions.id, sessionId));

                return {
                    success: true,
                    postId: session.generatedPostId,
                    status: action === "publish" ? "published" : "draft",
                    message: action === "publish" ? "Post published successfully" : "Draft saved",
                };
            } catch (err) {
                request.log.error(err);
                return reply.status(500).send({
                    success: false,
                    error: { message: err instanceof Error ? err.message : "Failed to update post status" },
                });
            }
        }
    );
};
